<a href="https://colab.research.google.com/github/seulayoon/PyTorch-Tutorial/blob/main/Tensors_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

Tensor는 Numpy의 ndarray와 유사, GPU를 사용한 연산 가속도 가능

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3) # 초기화되지 않은 행렬 생성
print(x)

tensor([[4.8996e-01, 3.0941e-41, 3.3631e-44],
        [0.0000e+00,        nan, 3.0941e-41],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.5760e-01]])


In [3]:
x = torch.rand(5, 3) # 무작위로 초기화된 행렬 생성
print(x)

tensor([[0.6115, 0.2066, 0.7528],
        [0.9410, 0.8530, 0.9193],
        [0.0360, 0.2277, 0.4965],
        [0.5259, 0.1349, 0.8035],
        [0.4738, 0.5430, 0.0595]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long) # dtype이 long이고 0으로 채워진 행렬 생성
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3]) # 데이터로부터 tensor를 직접 생성
print(x)

tensor([5.5000, 3.0000])


In [6]:
# 기존 tensor를 바탕으로 새로운 tensor 생성. 
# 이들 메소드는 사용자로부터 새로운 값을 제공받지 않은 한, 입력 tensor의 속성들(예. dtype)을 재사용.
x = x.new_ones(5, 3, dtype = torch.double) # new_* 메소드는 크기를 받는다.
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x, dtype=torch.float) # dtype을 오버라이드한다.
print(x) # 결과는 동일한 크기를 갖는다.

tensor([[-1.7690,  0.0720,  0.5766],
        [ 0.5779,  0.4380,  0.1106],
        [ 2.0315, -0.5889,  0.1159],
        [-1.3712, -0.1151, -2.1845],
        [ 0.5825,  1.0251, -1.6164]])


In [8]:
print(x.size())

torch.Size([5, 3])


torch.Size는 튜플(tuple) 타입으로, 모든 튜플 연산을 지원한다.

# 연산(Operations)

In [9]:
    y = torch.rand(5, 3)
    print(x + y)

tensor([[-0.8855,  1.0549,  1.0769],
        [ 1.4198,  1.2943,  0.5960],
        [ 2.9666, -0.1665,  0.2059],
        [-1.0583,  0.0980, -1.8579],
        [ 1.0857,  1.2477, -0.6385]])


In [10]:
print(torch.add(x, y))

tensor([[-0.8855,  1.0549,  1.0769],
        [ 1.4198,  1.2943,  0.5960],
        [ 2.9666, -0.1665,  0.2059],
        [-1.0583,  0.0980, -1.8579],
        [ 1.0857,  1.2477, -0.6385]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result) # 결과 tensor를 인자로 제공 
print(result)

tensor([[-0.8855,  1.0549,  1.0769],
        [ 1.4198,  1.2943,  0.5960],
        [ 2.9666, -0.1665,  0.2059],
        [-1.0583,  0.0980, -1.8579],
        [ 1.0857,  1.2477, -0.6385]])


덧셈: 바꿔치기(in-place)방식

In [12]:
y.add_(x) # y에 x 더하기
print(y)

tensor([[-0.8855,  1.0549,  1.0769],
        [ 1.4198,  1.2943,  0.5960],
        [ 2.9666, -0.1665,  0.2059],
        [-1.0583,  0.0980, -1.8579],
        [ 1.0857,  1.2477, -0.6385]])


바꿔치기(in-place) 방식으로 tensor의 값을 변경하는 연산 뒤에는 '__'가 붙는다. 
예: x.copy_(y), x.t_()는 x를 변경한다.

In [13]:
print(x[:, 1]) # 인덱싱 사용

tensor([ 0.0720,  0.4380, -0.5889, -0.1151,  1.0251])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view를 사용


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1은 다른 차원에서 유추
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


만약 tensor에 하나의 값만 존재한다면, .item()을 사용하면 숫자 값을 얻을 수 있다.

In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0362])
1.0361651182174683


# NumPy 변환(Bridge)

Torch Tensor를 NumPy 배열로 변환하거나, 그 반대로 하는 것
(Torch Tensor가 CPU 상에 있다면) Torch Tensor와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.

## Torch Tensor를 NumPy 배열로 변환하기

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## NumPy 배열을 Torch Tensor로 변환하기

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로 변환할 수 있고, 반대 변환도 가능

# CUDA Tensors

.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있다.

In [20]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행
# 'torch.device'를 사용하여 tensor를 GPU 안팎으로 이동

if torch.cuda.is_available():
  device = torch.device("cuda") # CUDA 장치 객체(device object)로
  y = torch.ones_like(x, device=device) # GPU 상에 직접적으로 tensor를 생성하거나
  x = x.to(device) # '.to("cuda")'를 사용하면 된다.
  z = x + y
  print(z)
  print(z.to("cpu", torch.double)) # '.to'는 dtype도 함께 변경한다.

tensor([2.0362], device='cuda:0')
tensor([2.0362], dtype=torch.float64)
